### insert and delete  ###

In [11]:
#insert
import numpy as np
var = np.array([1,2,3,4])
print(var)
print(type(var))
print(var.ndim)
print()

v = np.insert(var,[2],333)
print(v)

[1 2 3 4]
<class 'numpy.ndarray'>
1

[  1   2 333   3   4]


In [14]:
#multipl position
var = np.array([1,2,3,4])
print(var)
print(type(var))
print(var.ndim)
print()

v = np.insert(var,[2,4],333)
print(v)
#it can not assign float value
#it will give in round about and assign inform of integer

[1 2 3 4]
<class 'numpy.ndarray'>
1

[  1   2 333   3   4 333]


In [15]:
#two dimension 
var1 = np.array([[1,2,3,4],[5,6,7,8]])

v1 = np.insert(var1,2,6 , axis=0)
print(v1)

[[1 2 3 4]
 [5 6 7 8]
 [6 6 6 6]]


In [17]:
#two dimension for row
var1 = np.array([[1,2,3,4],[5,6,7,8]])

v1 = np.insert(var1,2,6 , axis=1)
print(v1)
#inform of row

[[1 2 6 3 4]
 [5 6 6 7 8]]


In [24]:
#inserting multiple data
#two dimension 
var3 = np.array([[1,2,3,4],[5,6,7,8]])

v1 = np.insert(var3,2,[6,4,5,6], axis=0)
print(v1)

[[1 2 3 4]
 [5 6 7 8]
 [6 4 5 6]]


In [32]:
#append 
var4 = np.array([[1,2],[7,8]])

v4 = np.append(var4,[[33,44]],axis=0)
print(v4)

[[ 1  2]
 [ 7  8]
 [33 44]]


In [35]:
#Dlete
vard = np.array([1,2,3,4])  
d = np.delete(vard,[2])
print(d)

[1 2 4]
